<?
  include_once ("../../../lib/inc.php");

  $api = CURL_Internals ("https://accounts.spotify.com/api/token", false, Array (SPOTIFYID, SPOTIFYSECRET), "code={$_REQUEST['code']}&grant_type=authorization_code&redirect_uri=rnsr://auth", false);
  
  echo $api;

  $fp = fopen (DEBUG, "w");
  fwrite ($fp, "code={$_REQUEST['code']}&grant_type=authorization_code&redirect_uri=rnmktest://auth". "\n\n". $api);
  fclose ($fp);
?>
